#!/usr/bin/env python3
"""Export BibTeX entries for Phase 3 included papers into the dissertation refs/.

Reads:
  - lit-review/coding/lit_review.db             (paper coding)
  - lit-review/searches/**/*.bib                 (raw ACM BibTeX exports)
  - lit-review/coding/matrix-papers.txt          (optional, with --matrix-only)

Writes:
  - brothrock-dissertation/refs/lit-review.bib   (consolidated, committed)

Usage:
    uv run python scripts/export_bibtex.py
    uv run python scripts/export_bibtex.py --matrix-only
"""

from __future__ import annotations

import argparse
import html
import re
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

import bibtexparser
from bibtexparser.bparser import BibTexParser

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent

DB_PATH = REPO_ROOT / "lit-review" / "coding" / "lit_review.db"
SEARCHES_DIR = REPO_ROOT / "lit-review" / "searches"
LIST_PATH = REPO_ROOT / "lit-review" / "coding" / "matrix-papers.txt"
OUT_PATH = REPO_ROOT / "brothrock-dissertation" / "refs" / "lit-review.bib"


def phase3_included_bibkeys(conn: sqlite3.Connection) -> set[str]:
    cur = conn.execute(
        "SELECT d.bibtex_key "
        "FROM document d JOIN pass_review pr ON pr.document_id = d.id "
        "WHERE pr.pass_number = 3 AND pr.decision = 'include'"
    )
    return {row[0] for row in cur}


def matrix_bibkeys(path: Path) -> set[str]:
    keys: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        keys.add(line)
    return keys


# Fields ACM exports contain that biblatex doesn't need for rendering and that
# sometimes carry unescaped LaTeX specials (e.g. raw `%` in abstract). Dropping
# them avoids runaway-string errors when pdflatex reads the .bbl.
STRIP_FIELDS = {"abstract", "keywords"}

# ACM exports sometimes contain HTML entities (&amp;, &nbsp;) or stray unescaped
# ampersands. biber passes these through verbatim, and LaTeX then treats `&`
# as a table alignment tab in \printbibliography, producing "Misplaced
# alignment tab character" errors. Sanitize field values before writing.
_AMPERSAND_ESCAPE_RE = re.compile(r"(?<!\\)&")


def sanitize_field(value: str) -> str:
    """Decode HTML entities and escape bare ampersands for LaTeX safety."""
    # Decode entities: &amp; -> &, &nbsp; -> \xa0, &#x2013; -> –, etc.
    decoded = html.unescape(value)
    # Non-breaking space -> LaTeX ~ (an explicit nbsp).
    decoded = decoded.replace("\u00a0", "~")
    # Escape any remaining bare & (not already preceded by a backslash).
    decoded = _AMPERSAND_ESCAPE_RE.sub(r"\\&", decoded)
    return decoded


def load_entries(searches_dir: Path) -> dict[str, dict]:
    """Return {bibkey: entry_dict} from every .bib under searches/. Later files win on duplicates."""
    parser = BibTexParser(common_strings=True)
    parser.ignore_nonstandard_types = False
    merged: dict[str, dict] = {}
    for bib_path in sorted(searches_dir.rglob("*.bib")):
        with bib_path.open("r", encoding="utf-8") as f:
            db = bibtexparser.load(f, parser=parser)
        for entry in db.entries:
            key = entry.get("ID")
            if not key:
                continue
            for f in STRIP_FIELDS:
                entry.pop(f, None)
            # Sanitize every remaining field value. ENTRYTYPE and ID stay raw.
            for k, v in list(entry.items()):
                if k in ("ENTRYTYPE", "ID"):
                    continue
                if isinstance(v, str):
                    entry[k] = sanitize_field(v)
            merged[key] = entry
    return merged


def write_bib(entries: list[dict], out_path: Path, included_count: int) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    db = bibtexparser.bibdatabase.BibDatabase()
    # Sort for stable diffs.
    db.entries = sorted(entries, key=lambda e: e.get("ID", ""))

    writer = bibtexparser.bwriter.BibTexWriter()
    writer.indent = "  "
    writer.align_values = False
    writer.order_entries_by = ("ID",)

    body = writer.write(db)

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = (
        f"% Consolidated BibTeX for the Chapter 2 literature review.\n"
        f"% Generated by lit-review/scripts/export_bibtex.py on {stamp}.\n"
        f"% Do not edit by hand -- rerun the script to refresh.\n"
        f"%\n"
        f"% Source: lit-review/searches/**/*.bib (ACM exports)\n"
        f"% Scope:  {included_count} entries ({len(entries)} written)\n\n"
    )

    out_path.write_text(header + body, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Export BibTeX for Ch. 2 paper set.")
    ap.add_argument(
        "--matrix-only",
        action="store_true",
        help="Restrict to bibkeys listed in matrix-papers.txt (intersection with Phase 3 includes).",
    )
    args = ap.parse_args()

    if not DB_PATH.exists():
        print(f"error: database not found at {DB_PATH}", file=sys.stderr)
        return 1
    if not SEARCHES_DIR.exists():
        print(f"error: searches dir not found at {SEARCHES_DIR}", file=sys.stderr)
        return 1

    conn = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    try:
        wanted = phase3_included_bibkeys(conn)
    finally:
        conn.close()

    if args.matrix_only:
        if not LIST_PATH.exists():
            print(f"error: --matrix-only but {LIST_PATH} does not exist", file=sys.stderr)
            return 1
        wanted &= matrix_bibkeys(LIST_PATH)

    all_entries = load_entries(SEARCHES_DIR)
    matched = [all_entries[k] for k in wanted if k in all_entries]
    missing = sorted(wanted - all_entries.keys())

    write_bib(matched, OUT_PATH, included_count=len(wanted))

    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    print(f"  wanted: {len(wanted)}  matched: {len(matched)}  missing: {len(missing)}")
    if missing:
        print("  missing bibkeys (not found in searches/**/*.bib):", file=sys.stderr)
        for k in missing:
            print(f"    {k}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
